### ISSUE TITLE
Generate more documentation

### ISSUE THREAD

**Issue by omtcyfz** [omtcyfz/heathen#6]
### User documentation

Enabling user documentation is crucial for a positive experience for those willing to learn more about the project.

[MkDocs](http://www.mkdocs.org/) can be used for generating documentation containing design notes, tutorials and other information relevant to the users from Markdown text files.

### Developer documentation

It is currently possible to get Doxygen-generated docs for developer reference (Doxygen config is stored in `docs/Codebase`). However, it can be configured to generate more fancy stuff like dependency diagrams and get a better look.

### Roadmap

* [ ] Start adding design notes and information about the project to organized `docs/Reference` directory
* [ ] Configure CMake and create MkDocs config for documentation generation
* [ ] Add optional MkDocs dependency, update README
* [ ] Start building both user and developer documentation in CI (probably create a single matrix entry for documentation and code coverage measurement for #1, this entry would be using `Debug` building type)
* [ ] Upload documentation somewhere (e.g. using Github pages `omtcyfz.github.io/heathen/docs/` if that is possible)
